version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=springcertification
